-- ============================================================
-- CoinJecko / Finance Hub — one-paste database bootstrap
--
-- GENERATED: concatenation of supabase/migrations/0001..0007 plus
-- seed.sql, in order. Do not edit this file; edit the sources and
-- regenerate. Schema changes still go in NEW numbered migrations.
-- ============================================================



-- ============================================================
-- SOURCE: supabase/migrations/0001_identity_and_audit.sql
-- ============================================================

-- ============================================================
-- 0001 — Identity, RBAC and tamper-resistant audit trail
-- Apply with the Supabase CLI (supabase db push) or SQL editor.
-- Design: least privilege, RLS on every table, append-only audit.
-- ============================================================

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ------------------------------------------------------------
-- Roles
-- ------------------------------------------------------------
create type public.app_role as enum (
  'super_admin',
  'security_admin',
  'editor',
  'author',
  'market_data_manager',
  'video_manager',
  'advertising_manager',
  'newsletter_manager',
  'analyst'
);

-- Permission matrix (mirrored in src/lib/auth/permissions.ts).
create table public.role_permissions (
  role       public.app_role not null,
  permission text            not null,
  primary key (role, permission)
);

-- ------------------------------------------------------------
-- Profiles (1:1 with auth.users)
-- ------------------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  role         public.app_role,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Helper functions (SECURITY DEFINER, locked search_path)
-- ------------------------------------------------------------
create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles
  where id = auth.uid() and is_active
$$;

create or replace function public.has_permission(required text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role_permissions rp
    where rp.role = public.current_app_role()
      and rp.permission = required
  )
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() = 'super_admin'
$$;

-- ------------------------------------------------------------
-- Profiles RLS
-- ------------------------------------------------------------
alter table public.profiles enable row level security;

create policy "profiles: read own"
  on public.profiles for select
  using (id = auth.uid());

create policy "profiles: user managers read all"
  on public.profiles for select
  using (public.has_permission('users.manage'));

create policy "profiles: update own non-privileged fields"
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- Role changes and activation are service-role/API-only; a trigger
-- blocks privilege escalation through self-service updates.
create or replace function public.prevent_privilege_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.role is distinct from old.role or new.is_active is distinct from old.is_active)
     and not public.has_permission('roles.assign')
     and current_setting('request.jwt.claims', true) is not null then
    raise exception 'changing role or activation requires roles.assign permission';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_profiles_privilege_guard
  before update on public.profiles
  for each row execute function public.prevent_privilege_escalation();

-- role_permissions: readable by any authenticated staff member,
-- writable only via service role (no policies grant write).
alter table public.role_permissions enable row level security;

create policy "role_permissions: authenticated read"
  on public.role_permissions for select
  to authenticated
  using (true);

-- ------------------------------------------------------------
-- Audit log — append-only, tamper-resistant
-- ------------------------------------------------------------
create table public.audit_log (
  id         bigint generated always as identity primary key,
  actor_id   uuid,
  action     text not null,
  entity     text not null,
  entity_id  text,
  metadata   jsonb not null default '{}'::jsonb,
  ip         inet,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

create policy "audit: readable with audit.read"
  on public.audit_log for select
  using (public.has_permission('audit.read'));

-- No insert/update/delete policies: only the service role writes.
-- Belt-and-braces: block UPDATE/DELETE even for privileged roles.
create or replace function public.audit_log_immutable()
returns trigger
language plpgsql
as $$
begin
  raise exception 'audit_log is append-only';
end;
$$;

create trigger trg_audit_log_no_update
  before update or delete on public.audit_log
  for each row execute function public.audit_log_immutable();

revoke update, delete on public.audit_log from anon, authenticated;

-- ------------------------------------------------------------
-- Login events (anomaly detection source)
-- ------------------------------------------------------------
create table public.login_events (
  id         bigint generated always as identity primary key,
  user_id    uuid,
  email_hash text,          -- sha256 of email; raw email is never stored here
  success    boolean not null,
  ip         inet,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.login_events enable row level security;

create policy "login_events: readable with audit.read"
  on public.login_events for select
  using (public.has_permission('audit.read'));

create trigger trg_login_events_no_update
  before update or delete on public.login_events
  for each row execute function public.audit_log_immutable();

revoke update, delete on public.login_events from anon, authenticated;

-- ------------------------------------------------------------
-- Generic row-change audit trigger for content tables
-- (attached per-table in later migrations)
-- ------------------------------------------------------------
create or replace function public.log_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_log (actor_id, action, entity, entity_id, metadata)
  values (
    auth.uid(),
    tg_table_name || '.' || lower(tg_op),
    tg_table_name,
    coalesce(
      case when tg_op = 'DELETE' then (to_jsonb(old) ->> 'id')
           else (to_jsonb(new) ->> 'id') end,
      ''
    ),
    jsonb_build_object('op', tg_op)
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

-- ------------------------------------------------------------
-- updated_at convenience trigger
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ------------------------------------------------------------
-- Seed the permission matrix (idempotent)
-- ------------------------------------------------------------
insert into public.role_permissions (role, permission) values
  -- super_admin: everything
  ('super_admin', 'content.create'), ('super_admin', 'content.edit_own'),
  ('super_admin', 'content.edit_any'), ('super_admin', 'content.review'),
  ('super_admin', 'content.publish'), ('super_admin', 'content.delete'),
  ('super_admin', 'taxonomy.manage'), ('super_admin', 'media.upload'),
  ('super_admin', 'media.manage_video'), ('super_admin', 'media.manage_podcast'),
  ('super_admin', 'market_data.manage'), ('super_admin', 'market_data.configure_providers'),
  ('super_admin', 'ads.manage'), ('super_admin', 'newsletter.manage'),
  ('super_admin', 'users.manage'), ('super_admin', 'roles.assign'),
  ('super_admin', 'audit.read'), ('super_admin', 'security.configure'),
  -- security_admin
  ('security_admin', 'audit.read'), ('security_admin', 'security.configure'),
  ('security_admin', 'users.manage'), ('security_admin', 'roles.assign'),
  -- editor
  ('editor', 'content.create'), ('editor', 'content.edit_own'),
  ('editor', 'content.edit_any'), ('editor', 'content.review'),
  ('editor', 'content.publish'), ('editor', 'content.delete'),
  ('editor', 'taxonomy.manage'), ('editor', 'media.upload'),
  -- author
  ('author', 'content.create'), ('author', 'content.edit_own'),
  ('author', 'media.upload'),
  -- market_data_manager
  ('market_data_manager', 'market_data.manage'),
  ('market_data_manager', 'market_data.configure_providers'),
  -- video_manager
  ('video_manager', 'media.upload'), ('video_manager', 'media.manage_video'),
  -- advertising_manager
  ('advertising_manager', 'ads.manage'),
  -- newsletter_manager
  ('newsletter_manager', 'newsletter.manage'),
  -- analyst
  ('analyst', 'content.create'), ('analyst', 'content.edit_own')
on conflict do nothing;


-- ============================================================
-- SOURCE: supabase/migrations/0002_content.sql
-- ============================================================

-- ============================================================
-- 0002 — Editorial content system
-- Bilingual articles (per-locale translations), editorial
-- workflow, media, comments, newsletter, advertising.
-- Public reads only published content; writes require permissions.
-- ============================================================

create type public.content_status as enum
  ('draft', 'review', 'approved', 'published', 'archived');

create type public.article_type as enum
  ('breaking_news', 'market_update', 'explainer', 'analysis',
   'opinion', 'interview', 'sponsored');

create type public.locale_code as enum ('en', 'ur');

-- ------------------------------------------------------------
-- Authors (public editorial identity; distinct from login users)
-- ------------------------------------------------------------
create table public.authors (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid references public.profiles (id) on delete set null,
  slug        text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name        text not null,
  title       text,
  bio         text,
  expertise   text[],
  avatar_path text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Taxonomy
-- ------------------------------------------------------------
create table public.categories (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique check (slug ~ '^[a-z0-9-]+$'),
  parent_id  uuid references public.categories (id) on delete set null,
  name_en    text not null,
  name_ur    text,
  created_at timestamptz not null default now()
);

create table public.tags (
  id      uuid primary key default gen_random_uuid(),
  slug    text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_en text not null,
  name_ur text
);

-- ------------------------------------------------------------
-- Articles: locale-neutral base + per-locale translations
-- ------------------------------------------------------------
create table public.articles (
  id            uuid primary key default gen_random_uuid(),
  article_type  public.article_type not null default 'market_update',
  status        public.content_status not null default 'draft',
  author_id     uuid references public.authors (id),
  category_id   uuid references public.categories (id),
  created_by    uuid not null references public.profiles (id),
  reviewed_by   uuid references public.profiles (id),
  is_sponsored  boolean not null default false,
  sponsor_name  text,
  hero_image_path text,
  published_at  timestamptz,
  scheduled_for timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- sponsored content must always carry a sponsor label
  constraint sponsored_needs_sponsor
    check (not is_sponsored or sponsor_name is not null),
  constraint published_needs_timestamp
    check (status <> 'published' or published_at is not null)
);

create table public.article_translations (
  id               uuid primary key default gen_random_uuid(),
  article_id       uuid not null references public.articles (id) on delete cascade,
  locale           public.locale_code not null,
  slug             text not null check (slug ~ '^[a-z0-9-]+$'),
  title            text not null,
  excerpt          text,
  body             text not null default '',
  seo_title        text,
  seo_description  text,
  sources          jsonb not null default '[]'::jsonb, -- [{name,url}]
  correction_notes jsonb not null default '[]'::jsonb, -- [{date,note}]
  is_machine_translated boolean not null default false,
  reviewed_translation  boolean not null default false,
  unique (article_id, locale),
  unique (locale, slug)
);

create table public.article_tags (
  article_id uuid not null references public.articles (id) on delete cascade,
  tag_id     uuid not null references public.tags (id) on delete cascade,
  primary key (article_id, tag_id)
);

-- ------------------------------------------------------------
-- Media
-- ------------------------------------------------------------
create table public.videos (
  id           uuid primary key default gen_random_uuid(),
  status       public.content_status not null default 'draft',
  locale       public.locale_code not null default 'en',
  title        text not null,
  slug         text not null unique check (slug ~ '^[a-z0-9-]+$'),
  description  text,
  provider     text,             -- e.g. 'youtube' | 'self_hosted'
  provider_ref text,             -- external id; validated server-side
  is_short     boolean not null default false,
  duration_s   integer check (duration_s is null or duration_s >= 0),
  created_by   uuid not null references public.profiles (id),
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table public.podcasts (
  id           uuid primary key default gen_random_uuid(),
  status       public.content_status not null default 'draft',
  locale       public.locale_code not null default 'en',
  title        text not null,
  slug         text not null unique check (slug ~ '^[a-z0-9-]+$'),
  description  text,
  audio_path   text,
  episode_no   integer,
  duration_s   integer check (duration_s is null or duration_s >= 0),
  created_by   uuid not null references public.profiles (id),
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Comments (pre-moderated)
-- ------------------------------------------------------------
create type public.comment_status as enum ('pending', 'approved', 'rejected');

create table public.comments (
  id         uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles (id) on delete cascade,
  user_id    uuid references auth.users (id) on delete set null,
  status     public.comment_status not null default 'pending',
  body       text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Newsletter (minimum data, explicit consent, double opt-in)
-- ------------------------------------------------------------
create table public.newsletter_subscribers (
  id                uuid primary key default gen_random_uuid(),
  email             citext not null unique,
  locale            public.locale_code not null default 'en',
  consent_given_at  timestamptz not null default now(),
  consent_source    text,                    -- which form/page
  confirmed_at      timestamptz,             -- double opt-in confirmation
  confirm_token     uuid not null default gen_random_uuid(),
  unsubscribe_token uuid not null default gen_random_uuid(),
  unsubscribed_at   timestamptz,
  created_at        timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Advertising (always labelled; see Advertising Disclosure page)
-- ------------------------------------------------------------
create table public.advertisements (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  kind        text not null check (kind in
                ('adsense', 'direct', 'sponsored_article', 'affiliate',
                 'newsletter_sponsor', 'podcast_sponsor')),
  placement   text not null,
  target_url  text,
  image_path  text,
  label       text not null default 'Advertisement',
  starts_at   timestamptz,
  ends_at     timestamptz,
  is_active   boolean not null default false,
  created_by  uuid not null references public.profiles (id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Row-Level Security
-- ------------------------------------------------------------
alter table public.authors               enable row level security;
alter table public.categories            enable row level security;
alter table public.tags                  enable row level security;
alter table public.articles              enable row level security;
alter table public.article_translations  enable row level security;
alter table public.article_tags          enable row level security;
alter table public.videos                enable row level security;
alter table public.podcasts              enable row level security;
alter table public.comments              enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.advertisements        enable row level security;

-- Public (anon) read access: published editorial surfaces only.
create policy "authors: public read active"
  on public.authors for select using (is_active);

create policy "categories: public read"
  on public.categories for select using (true);

create policy "tags: public read"
  on public.tags for select using (true);

create policy "articles: public read published"
  on public.articles for select
  using (status = 'published' or public.has_permission('content.review'));

create policy "translations: public read for published articles"
  on public.article_translations for select
  using (
    exists (
      select 1 from public.articles a
      where a.id = article_id
        and (a.status = 'published' or public.has_permission('content.review'))
    )
  );

create policy "article_tags: public read"
  on public.article_tags for select using (true);

create policy "videos: public read published"
  on public.videos for select
  using (status = 'published' or public.has_permission('content.review'));

create policy "podcasts: public read published"
  on public.podcasts for select
  using (status = 'published' or public.has_permission('content.review'));

create policy "comments: public read approved"
  on public.comments for select
  using (status = 'approved' or public.has_permission('content.review'));

create policy "comments: signed-in users create pending"
  on public.comments for insert
  to authenticated
  with check (user_id = auth.uid() and status = 'pending');

-- newsletter_subscribers: NO public policies. Subscription flows run
-- through server routes with the service role; subscriber data is
-- readable only with newsletter.manage.
create policy "newsletter: managers read"
  on public.newsletter_subscribers for select
  using (public.has_permission('newsletter.manage'));

create policy "ads: public read active"
  on public.advertisements for select
  using (is_active or public.has_permission('ads.manage'));

-- Staff write access (permission-gated).
create policy "articles: create with content.create"
  on public.articles for insert
  to authenticated
  with check (public.has_permission('content.create') and created_by = auth.uid());

create policy "articles: edit own or any"
  on public.articles for update
  to authenticated
  using (
    (public.has_permission('content.edit_own') and created_by = auth.uid())
    or public.has_permission('content.edit_any')
  )
  with check (
    (public.has_permission('content.edit_own') and created_by = auth.uid())
    or public.has_permission('content.edit_any')
  );

create policy "articles: delete with content.delete"
  on public.articles for delete
  to authenticated
  using (public.has_permission('content.delete'));

create policy "translations: write follows article edit rights"
  on public.article_translations for all
  to authenticated
  using (
    exists (
      select 1 from public.articles a
      where a.id = article_id
        and ((public.has_permission('content.edit_own') and a.created_by = auth.uid())
             or public.has_permission('content.edit_any'))
    )
  )
  with check (
    exists (
      select 1 from public.articles a
      where a.id = article_id
        and ((public.has_permission('content.edit_own') and a.created_by = auth.uid())
             or public.has_permission('content.edit_any'))
    )
  );

create policy "article_tags: write follows taxonomy or edit rights"
  on public.article_tags for all
  to authenticated
  using (public.has_permission('content.edit_any') or public.has_permission('taxonomy.manage'))
  with check (public.has_permission('content.edit_any') or public.has_permission('taxonomy.manage'));

create policy "categories: manage with taxonomy.manage"
  on public.categories for all
  to authenticated
  using (public.has_permission('taxonomy.manage'))
  with check (public.has_permission('taxonomy.manage'));

create policy "tags: manage with taxonomy.manage"
  on public.tags for all
  to authenticated
  using (public.has_permission('taxonomy.manage'))
  with check (public.has_permission('taxonomy.manage'));

create policy "authors: manage with users.manage or editor rights"
  on public.authors for all
  to authenticated
  using (public.has_permission('content.edit_any') or public.has_permission('users.manage'))
  with check (public.has_permission('content.edit_any') or public.has_permission('users.manage'));

create policy "videos: manage with media.manage_video"
  on public.videos for all
  to authenticated
  using (public.has_permission('media.manage_video'))
  with check (public.has_permission('media.manage_video') and created_by = auth.uid());

create policy "podcasts: manage with media.manage_podcast"
  on public.podcasts for all
  to authenticated
  using (public.has_permission('media.manage_podcast'))
  with check (public.has_permission('media.manage_podcast') and created_by = auth.uid());

create policy "comments: moderate with content.review"
  on public.comments for update
  to authenticated
  using (public.has_permission('content.review'))
  with check (public.has_permission('content.review'));

create policy "ads: manage with ads.manage"
  on public.advertisements for all
  to authenticated
  using (public.has_permission('ads.manage'))
  with check (public.has_permission('ads.manage') and created_by = auth.uid());

-- ------------------------------------------------------------
-- updated_at + audit triggers
-- ------------------------------------------------------------
create trigger trg_authors_updated  before update on public.authors
  for each row execute function public.set_updated_at();
create trigger trg_articles_updated before update on public.articles
  for each row execute function public.set_updated_at();
create trigger trg_videos_updated   before update on public.videos
  for each row execute function public.set_updated_at();
create trigger trg_podcasts_updated before update on public.podcasts
  for each row execute function public.set_updated_at();
create trigger trg_ads_updated      before update on public.advertisements
  for each row execute function public.set_updated_at();

create trigger trg_audit_articles
  after insert or update or delete on public.articles
  for each row execute function public.log_row_change();
create trigger trg_audit_translations
  after insert or update or delete on public.article_translations
  for each row execute function public.log_row_change();
create trigger trg_audit_ads
  after insert or update or delete on public.advertisements
  for each row execute function public.log_row_change();
create trigger trg_audit_videos
  after insert or update or delete on public.videos
  for each row execute function public.log_row_change();
create trigger trg_audit_podcasts
  after insert or update or delete on public.podcasts
  for each row execute function public.log_row_change();

-- ------------------------------------------------------------
-- Useful indexes
-- ------------------------------------------------------------
create index idx_articles_status_published_at
  on public.articles (status, published_at desc);
create index idx_articles_category on public.articles (category_id);
create index idx_translations_locale_slug
  on public.article_translations (locale, slug);
create index idx_comments_article on public.comments (article_id, status);


-- ============================================================
-- SOURCE: supabase/migrations/0003_market_data.sql
-- ============================================================

-- ============================================================
-- 0003 — Market data: providers, exchanges, indices, stocks,
-- crypto, forex, commodities, economic calendar.
-- Reference data + quotes are publicly readable; every quote row
-- records its provider, timestamp and delay status so the UI can
-- honour the data-transparency rules.
-- Writes: market_data.manage only (ingestion runs server-side).
-- ============================================================

create table public.data_providers (
  id            uuid primary key default gen_random_uuid(),
  code          text not null unique check (code ~ '^[a-z0-9_]+$'),
  name          text not null,
  website       text,
  attribution   text,               -- required display attribution
  license_notes text,               -- usage / licensing constraints
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

create table public.exchanges (
  id         uuid primary key default gen_random_uuid(),
  code       text not null unique,          -- e.g. 'PSX', 'NYSE'
  name       text not null,
  country    text not null,
  region     text not null check (region in
               ('north_america','europe','asia_pacific','south_asia',
                'middle_east','other')),
  timezone   text not null,                 -- IANA, e.g. 'Asia/Karachi'
  -- trading sessions as [{"open":"09:32","close":"15:30"}] local time
  sessions   jsonb not null default '[]'::jsonb,
  trading_days int[] not null default '{1,2,3,4,5}', -- ISO dow, 1=Mon
  website    text,
  created_at timestamptz not null default now()
);

create table public.market_indices (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,         -- e.g. 'KSE100', 'SPX'
  slug        text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name        text not null,
  exchange_id uuid references public.exchanges (id),
  currency    text not null,
  region      text not null,
  description text,
  created_at  timestamptz not null default now()
);

create table public.index_quotes (
  id            bigint generated always as identity primary key,
  index_id      uuid not null references public.market_indices (id) on delete cascade,
  price         numeric(18,4) not null,
  change_abs    numeric(18,4),
  change_pct    numeric(9,4),
  as_of         timestamptz not null,
  provider_id   uuid references public.data_providers (id),
  is_delayed    boolean not null default true,
  delay_minutes integer,
  created_at    timestamptz not null default now()
);

create table public.stocks (
  id          uuid primary key default gen_random_uuid(),
  symbol      text not null,
  exchange_id uuid references public.exchanges (id),
  name        text not null,
  currency    text not null,
  sector      text,
  created_at  timestamptz not null default now(),
  unique (symbol, exchange_id)
);

create table public.crypto_assets (
  id           uuid primary key default gen_random_uuid(),
  symbol       text not null unique,        -- e.g. 'BTC'
  slug         text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name         text not null,
  description  text,
  created_at   timestamptz not null default now()
);

create table public.crypto_quotes (
  id            bigint generated always as identity primary key,
  asset_id      uuid not null references public.crypto_assets (id) on delete cascade,
  price_usd     numeric(24,8) not null,
  market_cap    numeric(24,2),
  volume_24h    numeric(24,2),
  supply_circulating numeric(24,2),
  supply_total  numeric(24,2),
  change_pct_24h numeric(9,4),
  as_of         timestamptz not null,
  provider_id   uuid references public.data_providers (id),
  created_at    timestamptz not null default now()
);

create table public.forex_pairs (
  id         uuid primary key default gen_random_uuid(),
  base_code  text not null,
  quote_code text not null,
  slug       text not null unique check (slug ~ '^[a-z0-9-]+$'), -- 'usd-pkr'
  created_at timestamptz not null default now(),
  unique (base_code, quote_code)
);

create table public.forex_quotes (
  id          bigint generated always as identity primary key,
  pair_id     uuid not null references public.forex_pairs (id) on delete cascade,
  rate        numeric(18,6) not null,
  change_pct  numeric(9,4),
  as_of       timestamptz not null,
  provider_id uuid references public.data_providers (id),
  created_at  timestamptz not null default now()
);

create table public.commodities (
  id         uuid primary key default gen_random_uuid(),
  code       text not null unique,          -- e.g. 'XAU', 'BRENT'
  slug       text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name       text not null,
  unit       text not null,                 -- 'oz', 'bbl'
  currency   text not null default 'USD',
  created_at timestamptz not null default now()
);

create table public.commodity_quotes (
  id           bigint generated always as identity primary key,
  commodity_id uuid not null references public.commodities (id) on delete cascade,
  price        numeric(18,4) not null,
  change_pct   numeric(9,4),
  as_of        timestamptz not null,
  provider_id  uuid references public.data_providers (id),
  created_at   timestamptz not null default now()
);

create table public.economic_events (
  id          uuid primary key default gen_random_uuid(),
  country     text not null,
  title       text not null,
  importance  text not null check (importance in ('low','medium','high')),
  event_time  timestamptz not null,
  actual      text,
  forecast    text,
  previous    text,
  provider_id uuid references public.data_providers (id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
-- RLS: public read, manager write
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'data_providers','exchanges','market_indices','index_quotes',
    'stocks','crypto_assets','crypto_quotes','forex_pairs','forex_quotes',
    'commodities','commodity_quotes','economic_events'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy "%s: public read" on public.%I for select using (true)',
      t, t);
    execute format(
      'create policy "%s: manage with market_data.manage" on public.%I
         for all to authenticated
         using (public.has_permission(''market_data.manage''))
         with check (public.has_permission(''market_data.manage''))',
      t, t);
  end loop;
end $$;

create trigger trg_econ_events_updated
  before update on public.economic_events
  for each row execute function public.set_updated_at();

-- Provider configuration changes are security-relevant: audit them.
create trigger trg_audit_data_providers
  after insert or update or delete on public.data_providers
  for each row execute function public.log_row_change();

-- ------------------------------------------------------------
-- Quote lookup indexes (latest-quote queries)
-- ------------------------------------------------------------
create index idx_index_quotes_latest
  on public.index_quotes (index_id, as_of desc);
create index idx_crypto_quotes_latest
  on public.crypto_quotes (asset_id, as_of desc);
create index idx_forex_quotes_latest
  on public.forex_quotes (pair_id, as_of desc);
create index idx_commodity_quotes_latest
  on public.commodity_quotes (commodity_id, as_of desc);
create index idx_econ_events_time
  on public.economic_events (event_time desc, importance);


-- ============================================================
-- SOURCE: supabase/migrations/0004_editorial_workflow_guard.sql
-- ============================================================

-- ============================================================
-- 0004 — Editorial workflow guard
--
-- 0002's "articles: edit own or any" UPDATE policy gates *who* may
-- edit a row, but not *which* status they may move it to. An author
-- (content.edit_own, no content.publish) could therefore set
-- status = 'published' on their own draft and reach the public site,
-- because the public read policy keys off status alone.
--
-- RLS cannot express this on its own: WITH CHECK sees only NEW, so it
-- cannot compare against the previous status. A BEFORE UPDATE trigger
-- can, so the transition rules live here — making the database the
-- enforcement boundary the security model claims it is, rather than
-- relying on the TypeScript mirror in src/lib/content/workflow.ts.
-- ============================================================

create or replace function public.enforce_editorial_workflow()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- No JWT claims = service-role, migration or seed context. Those are
  -- already trusted (mirrors prevent_privilege_escalation in 0001).
  if current_setting('request.jwt.claims', true) is null then
    return new;
  end if;

  if new.status is distinct from old.status then

    -- Entering or leaving 'published' changes public visibility.
    if new.status = 'published' or old.status = 'published' then
      if not public.has_permission('content.publish') then
        raise exception
          'changing publication state requires the content.publish permission';
      end if;

    -- Clearing an article for publication is the reviewer's gate.
    elsif new.status = 'approved' then
      if not public.has_permission('content.review') then
        raise exception
          'approving content requires the content.review permission';
      end if;
    end if;

    -- Only the transitions the editorial workflow actually defines.
    if not (
         (old.status = 'draft'     and new.status in ('review', 'published', 'archived'))
      or (old.status = 'review'    and new.status in ('draft', 'approved', 'archived'))
      or (old.status = 'approved'  and new.status in ('review', 'published', 'archived'))
      or (old.status = 'published' and new.status in ('draft', 'archived'))
      or (old.status = 'archived'  and new.status = 'draft')
    ) then
      raise exception 'illegal editorial transition: % -> %', old.status, new.status;
    end if;

    -- Keep published_needs_timestamp satisfied without trusting the
    -- caller to send a timestamp (and never backdate an existing one).
    if new.status = 'published' and new.published_at is null then
      new.published_at := now();
    end if;

    -- Record who moved it out of review, for the audit trail.
    if new.status in ('approved', 'published') and new.reviewed_by is null then
      new.reviewed_by := auth.uid();
    end if;
  end if;

  return new;
end;
$$;

comment on function public.enforce_editorial_workflow() is
  'Enforces content_status transition rules and their required permissions on public.articles.';

create trigger trg_articles_workflow_guard
  before update on public.articles
  for each row execute function public.enforce_editorial_workflow();

-- Inserts bypass the trigger above, so an author could otherwise create
-- a row already marked 'published'. 0002's insert policy only checks
-- content.create; tighten it to require content.publish for anything
-- that is born public.
drop policy if exists "articles: create with content.create" on public.articles;

create policy "articles: create with content.create"
  on public.articles for insert
  to authenticated
  with check (
    public.has_permission('content.create')
    and created_by = auth.uid()
    and (
      status in ('draft', 'review')
      or (status = 'approved'  and public.has_permission('content.review'))
      or (status = 'published' and public.has_permission('content.publish'))
    )
  );


-- ============================================================
-- SOURCE: supabase/migrations/0005_contact_messages.sql
-- ============================================================

-- ============================================================
-- 0005 — Contact form submissions
--
-- Anyone may submit; only staff holding users.manage may read. The
-- table is deliberately write-only from the public's side: a policy
-- that let submitters read rows back would expose every other
-- visitor's message and email address.
-- ============================================================

create type public.contact_topic as enum
  ('general', 'advertising', 'correction', 'data_request');

create table public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  topic      public.contact_topic not null default 'general',
  name       text not null check (length(trim(name)) between 1 and 120),
  email      text not null check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  message    text not null check (length(trim(message)) between 1 and 5000),
  -- Coarse abuse-tracing context. No cookies, no fingerprinting.
  ip         inet,
  user_agent text,
  handled_at timestamptz,
  handled_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index contact_messages_created_idx
  on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;

-- Submissions arrive through a server action using the service role,
-- so no INSERT policy is granted to anon/authenticated: there is no
-- public write path to abuse directly.
create policy "contact: staff read with users.manage"
  on public.contact_messages for select
  to authenticated
  using (public.has_permission('users.manage'));

create policy "contact: staff mark handled"
  on public.contact_messages for update
  to authenticated
  using (public.has_permission('users.manage'))
  with check (public.has_permission('users.manage'));

-- Row changes are audited like other content tables.
create trigger trg_audit_contact_messages
  after insert or update or delete on public.contact_messages
  for each row execute function public.log_row_change();


-- ============================================================
-- SOURCE: supabase/migrations/0006_public_editorial_surfaces.sql
-- ============================================================

-- ============================================================
-- 0006 — Public editorial surfaces: breaking news, blog, vlogs
--
-- No new tables: breaking news is `articles` with
-- article_type = 'breaking_news', the blog is the same table read by
-- published_at, and vlogs are `videos`. This migration fixes one
-- access-control gap and adds the indexes those read paths need.
-- ============================================================

-- 0002 let anyone with media.manage_video WRITE videos, but the SELECT
-- policy only admitted published rows or content.review. A
-- video_manager could therefore insert a draft and then not see it —
-- their own admin list came back empty. Managing a row implies reading
-- it, so the select policy has to admit the same permission.
drop policy if exists "videos: public read published" on public.videos;

create policy "videos: public read published"
  on public.videos for select
  using (
    status = 'published'
    or public.has_permission('content.review')
    or public.has_permission('media.manage_video')
  );

-- Same gap for podcasts, fixed now rather than left as a trap for
-- whoever builds that surface next.
drop policy if exists "podcasts: public read published" on public.podcasts;

create policy "podcasts: public read published"
  on public.podcasts for select
  using (
    status = 'published'
    or public.has_permission('content.review')
    or public.has_permission('media.manage_podcast')
  );

-- ------------------------------------------------------------
-- Read-path indexes
-- ------------------------------------------------------------

-- The breaking-news strip runs on every page render: newest published
-- rows of one article_type.
create index if not exists idx_articles_type_status_published
  on public.articles (article_type, status, published_at desc);

-- The vlog index: newest published videos, optionally per locale.
create index if not exists idx_videos_status_published
  on public.videos (status, published_at desc);

create index if not exists idx_videos_locale_status
  on public.videos (locale, status);


-- ============================================================
-- SOURCE: supabase/migrations/0007_profile_on_signup.sql
-- ============================================================

-- ============================================================
-- 0007 — Create a profile row when an account is created
--
-- 0001 defined public.profiles as 1:1 with auth.users but never wired
-- up the trigger that keeps them in step. The consequence only shows
-- at first use: someone signs up, no profile row exists, and
-- getCurrentUser() reads is_active as false — so the account is
-- created successfully and then behaves exactly like a banned one,
-- redirected away from /admin with no way to tell why.
--
-- The new profile deliberately gets role = NULL. is_active defaults to
-- true, but with no role has_permission() returns false for
-- everything, so a fresh account can sign in and do nothing until
-- somebody with roles.assign grants it a role. That is the
-- least-privilege default the security model already assumes.
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, split_part(coalesce(new.email, ''), '@', 1))
  on conflict (id) do nothing;
  return new;
end;
$$;

comment on function public.handle_new_user() is
  'Keeps public.profiles 1:1 with auth.users. New profiles carry no role.';

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill anyone who signed up before this trigger existed.
insert into public.profiles (id, display_name)
select u.id, split_part(coalesce(u.email, ''), '@', 1)
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id);


-- ============================================================
-- SOURCE: supabase/seed.sql
-- ============================================================

-- ============================================================
-- Seed: reference data only (no fabricated market prices).
-- Quotes arrive exclusively from licensed data providers.
-- ============================================================

-- Categories (Level 1 global topics)
insert into public.categories (slug, name_en, name_ur) values
  ('markets',          'Markets',          'مارکیٹس'),
  ('crypto',           'Crypto',           'کرپٹو'),
  ('forex',            'Forex',            'فاریکس'),
  ('commodities',      'Commodities',      'اجناس'),
  ('economy',          'Economy',          'معیشت'),
  ('business',         'Business',         'کاروبار'),
  ('personal-finance', 'Personal Finance', 'ذاتی مالیات'),
  ('technology',       'Technology',       'ٹیکنالوجی'),
  ('ai-fintech',       'AI & Fintech',     'اے آئی اور فن ٹیک')
on conflict (slug) do nothing;

-- Exchanges (sessions are regular local trading hours)
insert into public.exchanges (code, name, country, region, timezone, sessions, trading_days) values
  ('NYSE',   'New York Stock Exchange',   'United States',  'north_america', 'America/New_York',
   '[{"open":"09:30","close":"16:00"}]', '{1,2,3,4,5}'),
  ('NASDAQ', 'Nasdaq',                    'United States',  'north_america', 'America/New_York',
   '[{"open":"09:30","close":"16:00"}]', '{1,2,3,4,5}'),
  ('TSX',    'Toronto Stock Exchange',    'Canada',         'north_america', 'America/Toronto',
   '[{"open":"09:30","close":"16:00"}]', '{1,2,3,4,5}'),
  ('LSE',    'London Stock Exchange',     'United Kingdom', 'europe',        'Europe/London',
   '[{"open":"08:00","close":"16:30"}]', '{1,2,3,4,5}'),
  ('XETRA',  'Deutsche Börse Xetra',      'Germany',        'europe',        'Europe/Berlin',
   '[{"open":"09:00","close":"17:30"}]', '{1,2,3,4,5}'),
  ('EURONEXT-PA', 'Euronext Paris',       'France',         'europe',        'Europe/Paris',
   '[{"open":"09:00","close":"17:30"}]', '{1,2,3,4,5}'),
  ('SIX',    'SIX Swiss Exchange',        'Switzerland',    'europe',        'Europe/Zurich',
   '[{"open":"09:00","close":"17:30"}]', '{1,2,3,4,5}'),
  ('JPX',    'Japan Exchange Group (TSE)','Japan',          'asia_pacific',  'Asia/Tokyo',
   '[{"open":"09:00","close":"11:30"},{"open":"12:30","close":"15:00"}]', '{1,2,3,4,5}'),
  ('HKEX',   'Hong Kong Exchanges',       'Hong Kong',      'asia_pacific',  'Asia/Hong_Kong',
   '[{"open":"09:30","close":"12:00"},{"open":"13:00","close":"16:00"}]', '{1,2,3,4,5}'),
  ('SSE',    'Shanghai Stock Exchange',   'China',          'asia_pacific',  'Asia/Shanghai',
   '[{"open":"09:30","close":"11:30"},{"open":"13:00","close":"15:00"}]', '{1,2,3,4,5}'),
  ('SZSE',   'Shenzhen Stock Exchange',   'China',          'asia_pacific',  'Asia/Shanghai',
   '[{"open":"09:30","close":"11:30"},{"open":"13:00","close":"14:57"}]', '{1,2,3,4,5}'),
  ('KRX',    'Korea Exchange',            'South Korea',    'asia_pacific',  'Asia/Seoul',
   '[{"open":"09:00","close":"15:30"}]', '{1,2,3,4,5}'),
  ('TWSE',   'Taiwan Stock Exchange',     'Taiwan',         'asia_pacific',  'Asia/Taipei',
   '[{"open":"09:00","close":"13:30"}]', '{1,2,3,4,5}'),
  ('SGX',    'Singapore Exchange',        'Singapore',      'asia_pacific',  'Asia/Singapore',
   '[{"open":"09:00","close":"17:00"}]', '{1,2,3,4,5}'),
  ('ASX',    'Australian Securities Exchange', 'Australia', 'asia_pacific',  'Australia/Sydney',
   '[{"open":"10:00","close":"16:00"}]', '{1,2,3,4,5}'),
  ('PSX',    'Pakistan Stock Exchange',   'Pakistan',       'south_asia',    'Asia/Karachi',
   '[{"open":"09:32","close":"15:30"}]', '{1,2,3,4,5}'),
  ('NSE',    'National Stock Exchange of India', 'India',   'south_asia',    'Asia/Kolkata',
   '[{"open":"09:15","close":"15:30"}]', '{1,2,3,4,5}'),
  ('BSE',    'BSE (Bombay Stock Exchange)', 'India',        'south_asia',    'Asia/Kolkata',
   '[{"open":"09:15","close":"15:30"}]', '{1,2,3,4,5}'),
  ('TADAWUL','Saudi Exchange (Tadawul)',  'Saudi Arabia',   'middle_east',   'Asia/Riyadh',
   '[{"open":"10:00","close":"15:10"}]', '{7,1,2,3,4}'),
  ('DFM',    'Dubai Financial Market',    'United Arab Emirates', 'middle_east', 'Asia/Dubai',
   '[{"open":"10:00","close":"14:50"}]', '{1,2,3,4,5}'),
  ('ADX',    'Abu Dhabi Securities Exchange', 'United Arab Emirates', 'middle_east', 'Asia/Dubai',
   '[{"open":"10:00","close":"14:45"}]', '{1,2,3,4,5}'),
  ('QSE',    'Qatar Stock Exchange',      'Qatar',          'middle_east',   'Asia/Qatar',
   '[{"open":"09:30","close":"13:15"}]', '{7,1,2,3,4}'),
  ('BOURSAKW','Boursa Kuwait',            'Kuwait',         'middle_east',   'Asia/Kuwait',
   '[{"open":"09:30","close":"13:00"}]', '{7,1,2,3,4}'),
  ('BHB',    'Bahrain Bourse',            'Bahrain',        'middle_east',   'Asia/Bahrain',
   '[{"open":"09:30","close":"13:00"}]', '{7,1,2,3,4}'),
  ('MSX',    'Muscat Stock Exchange',     'Oman',           'middle_east',   'Asia/Muscat',
   '[{"open":"10:00","close":"14:00"}]', '{7,1,2,3,4}')
on conflict (code) do nothing;

-- Major indices (Level 3 market pages)
insert into public.market_indices (code, slug, name, exchange_id, currency, region) values
  ('DJI',    'dow-jones',          'Dow Jones Industrial Average', (select id from public.exchanges where code='NYSE'),   'USD', 'north_america'),
  ('SPX',    's-and-p-500',        'S&P 500',                      (select id from public.exchanges where code='NYSE'),   'USD', 'north_america'),
  ('IXIC',   'nasdaq-composite',   'Nasdaq Composite',             (select id from public.exchanges where code='NASDAQ'), 'USD', 'north_america'),
  ('RUT',    'russell-2000',       'Russell 2000',                 (select id from public.exchanges where code='NYSE'),   'USD', 'north_america'),
  ('GSPTSE', 'tsx-composite',      'S&P/TSX Composite',            (select id from public.exchanges where code='TSX'),    'CAD', 'north_america'),
  ('UKX',    'ftse-100',           'FTSE 100',                     (select id from public.exchanges where code='LSE'),    'GBP', 'europe'),
  ('MCX',    'ftse-250',           'FTSE 250',                     (select id from public.exchanges where code='LSE'),    'GBP', 'europe'),
  ('DAX',    'dax',                'DAX',                          (select id from public.exchanges where code='XETRA'),  'EUR', 'europe'),
  ('CAC',    'cac-40',             'CAC 40',                       (select id from public.exchanges where code='EURONEXT-PA'), 'EUR', 'europe'),
  ('SX5E',   'euro-stoxx-50',      'Euro Stoxx 50',                null,                                                   'EUR', 'europe'),
  ('IBEX',   'ibex-35',            'IBEX 35',                      null,                                                   'EUR', 'europe'),
  ('FTSEMIB','ftse-mib',           'FTSE MIB',                     null,                                                   'EUR', 'europe'),
  ('SMI',    'smi',                'Swiss Market Index',           (select id from public.exchanges where code='SIX'),    'CHF', 'europe'),
  ('NKY',    'nikkei-225',         'Nikkei 225',                   (select id from public.exchanges where code='JPX'),    'JPY', 'asia_pacific'),
  ('TPX',    'topix',              'TOPIX',                        (select id from public.exchanges where code='JPX'),    'JPY', 'asia_pacific'),
  ('HSI',    'hang-seng',          'Hang Seng Index',              (select id from public.exchanges where code='HKEX'),   'HKD', 'asia_pacific'),
  ('SHCOMP', 'shanghai-composite', 'Shanghai Composite',           (select id from public.exchanges where code='SSE'),    'CNY', 'asia_pacific'),
  ('SZCOMP', 'shenzhen-component', 'Shenzhen Component',           (select id from public.exchanges where code='SZSE'),   'CNY', 'asia_pacific'),
  ('KOSPI',  'kospi',              'KOSPI',                        (select id from public.exchanges where code='KRX'),    'KRW', 'asia_pacific'),
  ('TWII',   'taiwan-weighted',    'Taiwan Weighted Index',        (select id from public.exchanges where code='TWSE'),   'TWD', 'asia_pacific'),
  ('STI',    'straits-times',      'Straits Times Index',          (select id from public.exchanges where code='SGX'),    'SGD', 'asia_pacific'),
  ('AS51',   'asx-200',            'S&P/ASX 200',                  (select id from public.exchanges where code='ASX'),    'AUD', 'asia_pacific'),
  ('KSE100', 'kse-100',            'KSE-100',                      (select id from public.exchanges where code='PSX'),    'PKR', 'south_asia'),
  ('NIFTY',  'nifty-50',           'Nifty 50',                     (select id from public.exchanges where code='NSE'),    'INR', 'south_asia'),
  ('SENSEX', 'bse-sensex',         'BSE Sensex',                   (select id from public.exchanges where code='BSE'),    'INR', 'south_asia'),
  ('TASI',   'tadawul-tasi',       'Tadawul All Share (TASI)',     (select id from public.exchanges where code='TADAWUL'),'SAR', 'middle_east'),
  ('DFMGI',  'dfm-general',        'DFM General Index',            (select id from public.exchanges where code='DFM'),    'AED', 'middle_east'),
  ('ADSMI',  'adx-general',        'ADX General Index',            (select id from public.exchanges where code='ADX'),    'AED', 'middle_east'),
  ('QEAS',   'qe-index',           'QE Index',                     (select id from public.exchanges where code='QSE'),    'QAR', 'middle_east'),
  ('BKA',    'boursa-kuwait-all',  'Boursa Kuwait All Share',      (select id from public.exchanges where code='BOURSAKW'),'KWD','middle_east'),
  ('BAX',    'bahrain-all-share',  'Bahrain All Share',            (select id from public.exchanges where code='BHB'),    'BHD', 'middle_east'),
  ('MSM30',  'msx-30',             'MSX 30',                       (select id from public.exchanges where code='MSX'),    'OMR', 'middle_east')
on conflict (code) do nothing;

-- Core crypto assets, forex corridors and commodities
insert into public.crypto_assets (symbol, slug, name) values
  ('BTC',  'bitcoin',  'Bitcoin'),
  ('ETH',  'ethereum', 'Ethereum'),
  ('USDT', 'tether',   'Tether (USDT)'),
  ('XRP',  'xrp',      'XRP'),
  ('BNB',  'bnb',      'BNB'),
  ('SOL',  'solana',   'Solana'),
  ('ADA',  'cardano',  'Cardano')
on conflict (symbol) do nothing;

insert into public.forex_pairs (base_code, quote_code, slug) values
  ('USD', 'PKR', 'usd-pkr'),
  ('EUR', 'PKR', 'eur-pkr'),
  ('GBP', 'PKR', 'gbp-pkr'),
  ('AED', 'PKR', 'aed-pkr'),
  ('SAR', 'PKR', 'sar-pkr'),
  ('USD', 'INR', 'usd-inr'),
  ('EUR', 'USD', 'eur-usd'),
  ('GBP', 'USD', 'gbp-usd'),
  ('USD', 'JPY', 'usd-jpy'),
  ('USD', 'CAD', 'usd-cad')
on conflict (base_code, quote_code) do nothing;

insert into public.commodities (code, slug, name, unit, currency) values
  ('XAU',   'gold',      'Gold',            'oz',  'USD'),
  ('XAG',   'silver',    'Silver',          'oz',  'USD'),
  ('BRENT', 'brent-oil', 'Brent Crude Oil', 'bbl', 'USD'),
  ('WTI',   'wti-oil',   'WTI Crude Oil',   'bbl', 'USD')
on conflict (code) do nothing;
